title: Possible preparation for applicationframe.dll DLL Hijacking
id: 7730762b-2897-48a3-6541-5b9ff8503660
status: experimental
description: Detects possible DLL hijacking of applicationframe.dll by looking for suspicious file writes of this DLL, to unexpected locations.
references:
    - https://hijacklibs.net/entries/microsoft/built-in/applicationframe.html
author: "Wietze Beukema"
date: 2022-05-21
tags:
    - attack.defense_evasion
    - attack.T1574.001
logsource:
    product: windows
    category: file_event
detection:
    selection:
        TargetFileName: '*\applicationframe.dll'
    filter:
        TargetFileName:
            - 'c:\windows\system32\*'
            - 'c:\windows\syswow64\*'
            - 'c:\windows\winsxs\*'
            - 'c:\$windows.~bt\*'
            - 'c:\windows\softwaredistribution\*'

    condition: selection and not filter
falsepositives:
    - False positives are likely. This rule is more suitable for hunting than for generating detections.

