name: Transform "HijackLibs Image Load" Sigma rules to S1PQ

on:
  workflow_dispatch:
 
  schedule:
    - cron: "0 0 * * *"  # Run once per day at midnight

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Change value from 'self-hosted' to 'ubuntu-latest' if you want to host it on Github.
    permissions:
      contents: write
    env:
      SIGMACATEGORY: "HijackLibs"
      PLATFORM: "windows"
      SIGMARULE: "image_load"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10'
        
      - name: get sigma-cli # other parts of my CI/CD workflow use the sigma-cli - I've left it in, but you should be ok to remove this section and the plugin install steps too.
        run: |
          python -m pip install sigma-cli 
      
      - name: Install sigma-cli pipelines
        run: |
          sigma plugin install sentinelone-pq
        
      - name: Get Sigma file
        run: |
          mkdir -p "${{ github.workspace }}/${{ env.SIGMACATEGORY }}"
          cd '${{ env.SIGMACATEGORY }}'
          wget -O ./${{ env.PLATFORM }}-${{ env.SIGMARULE }}.yml https://hijacklibs.net/api/sigma_feed_image.yml
  
      - name: Create destination folder 'S1PQ-${{ env.SIGMACATEGORY }}-${{ env.PLATFORM }}-${{ env.SIGMARULE }}'
        run: |
          mkdir -p "${{ github.workspace }}/S1PQ-${{ env.SIGMACATEGORY }}-${{ env.PLATFORM }}-${{ env.SIGMARULE }}"
          cd 'S1PQ-${{ env.SIGMACATEGORY }}-${{ env.PLATFORM }}-${{ env.SIGMARULE }}'
      
      - name: Run 'sigma-to-s1pq-converter.py' script
        run: python sigma-to-s1pq-converter.py '${{ github.workspace }}/${{ env.SIGMACATEGORY }}/' 'S1PQ-${{ env.SIGMACATEGORY }}-${{ env.PLATFORM }}-${{ env.SIGMARULE }}'
  
      - name: Pull latest changes
        run: git pull origin main
  
      - name: Push changes
        run: git push origin main
  
      - name: Commit and push translated process creation rules
        uses: stefanzweifel/git-auto-commit-action@v5
