name: Update workflow_status.md with Workflow Status

on:
  schedule:
    - cron: '0 * * * *' # Exécute toutes les heures
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  update-workflow-status-md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get workflow status
      id: get_status
      run: |
        # Récupérer les états des workflows via l'API GitHub
        response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100")

        # Extraire les informations nécessaires
        echo "::set-output name=workflow_status::$(echo $response | jq -r '.workflow_runs[] | select(.status == "completed") | [.name, .conclusion, .updated_at] | @tsv')"

    - name: Update workflow_status.md
      run: |
        # Lire le contenu actuel du workflow_status.md
        workflow_status.md_content=$(cat workflow_status.md)

        # Ajouter le tableau des états des workflows
        workflow_status=$(echo "${{ steps.get_status.outputs.workflow_status }}" | tr '\n' '|' | sed 's/|$/\n/')
        table="| Workflow Name | Status | Last Updated |\n|--------------|--------|--------------|\n${workflow_status//$'\t'/|}"

        # Mettre à jour le workflow_status.md
        echo -e "${workflow_status.md_content}\n\n## Workflow Status\n\n${table}" > workflow_status.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add workflow_status.md
        git commit -m "Update workflow_status.md with workflow status"
        git push
